# transformer.tashkeela+clartts.yml

DATA:
  TRAIN_PATH: data/clartts/clartts_asr_train.tsv
  TEST_PATH: data/clartts/test.txt
  MAX_LENGTH: null

MODEL:
  TYPE: Transformer
  MAXLEN: 186
  VOCAB_SIZE: 77
  ASR_VOCAB_SIZE: 91
  D_MODEL: 128
  NUM_HEADS: 4
  DFF: 128
  NUM_BLOCKS: 5
  DROPOUT_RATE: 0.2
  OUTPUT_SIZE: 19
  USE_ASR: True
  WITH_CONN: False # use concatenation to combine
  PRETRAINED_PATH: checkpoints/transformer-tashkeela/best_model.pth
  LOAD_TEXT_BRANCH_ONLY: True

TRAIN:
  DEVICE: cuda
  BATCH_SIZE: 128
  NUM_EPOCHS: 20
  LEARNING_RATE: 0.001
  SAVE_DIR: checkpoints/transformer-tashkeela+clartts
  SAVE_FREQ: 40
  EVAL_FREQ: 1
  
INFERENCE:
  USE_ASR: False
  DEVICE: cuda
  BATCH_SIZE: 16
  MODEL_PATH: checkpoints/transformer-tashkeela+clartts/best_model.pth
  ASR_MODEL_NAME: "sashat/whisper-medium-ClassicalAr"
  OUTPUT_PATH: checkpoints/transformer-tashkeela+clartts/results/predictions.txt